### PR TITLE
pool: fix race condition at GetNextConnection()

### LINKED ISSUE #309: Data race on GetNextConnection in round-robin
Data race appear on [nextIndex](https://github.com/tarantool/go-tarantool/blob/337ca730e8c2dc3135bf0c49764253b4e2ba1421/pool/round_robin.go#L108)
As solution you can set mutex on Lock instead [RLock](https://github.com/tarantool/go-tarantool/blob/337ca730e8c2dc3135bf0c49764253b4e2ba1421/pool/round_robin.go#L74C10-L74C15)
Thanks
> ==================
WARNING: DATA RACE
Read at 0x00c0001d8ae0 by goroutine 41:
  github.com/tarantool/go-tarantool/v2/pool.(*roundRobinStrategy).nextIndex()
      /Users/s.skubach/go/pkg/mod/github.com/tarantool/go-tarantool/v2@v2.0.0-20230614085627-6cddcd71029d/pool/round_robin.go:107 +0x4c
  github.com/tarantool/go-tarantool/v2/pool.(*roundRobinStrategy).GetNextConnection()
      /Users/s.skubach/go/pkg/mod/github.com/tarantool/go-tarantool/v2@v2.0.0-20230614085627-6cddcd71029d/pool/round_robin.go:80 +0x1b5
  github.com/tarantool/go-tarantool/v2/pool.(*ConnectionPool).getNextConnection()
      /Users/s.skubach/go/pkg/mod/github.com/tarantool/go-tarantool/v2@v2.0.0-20230614085627-6cddcd71029d/pool/connection_pool.go:1261 +0x25d
  github.com/tarantool/go-tarantool/v2/pool.(*ConnectionPool).CallTyped()
      /Users/s.skubach/go/pkg/mod/github.com/tarantool/go-tarantool/v2@v2.0.0-20230614085627-6cddcd71029d/pool/connection_pool.go:564 +0xb1

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The `r.current` value can be changed by concurrent threads because the change happens under read-lock. We could use the atomic counter for a current connection number to avoid the race condition.

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)

Related issues:

Closes #309

### CODE REVIEW

**Review by DifferentialOrange — APPROVED** [review]

File: pool/connection_pool_test.go [hunk 1]
```diff
@@ -2215,6 +2215,35 @@ func TestDo(t *testing.T) {
 	require.NotNilf(t, resp, "response is nil after Ping")
 }
```
Comment (DifferentialOrange) [inline pool/connection_pool_test.go:2216]: It seems that expected approach is to write commit message as `subsystem: message` and `bugfix` is not a subsystem. It should something like `pool: fix race condition at GetNextConnection()`

Comment (oleg-jukovec) [reply pool/connection_pool_test.go:2216]: Done.

**Review by better0fdead — APPROVED** [review]
