### PR TITLE
crud: support `operation_data` field in errors

### LINKED ISSUE #330: crud: support `operation_data` in errors
We need to support a field named `operation_data` in errors from crud's `*many*` requests. [The field can contain](https://github.com/tarantool/crud/#insert-many):

* tuple for which the error occurred;
* object with an incorrect format;
* tuple the operation on which was performed but operation was rollback;
* tuple the operation on which was not performed because operation was stopped by error.

It would be nice to have an ability to decode the tuple/object into a custom type with `crud.Result` helper type:

https://github.com/tarantool/go-tarantool/blob/b17735b99c7ea8374019bd1ba60170be9b0290f1/crud/result.go#L52-L57

### PR DESCRIPTION
**Pull request by askalt**
This patch adds `operation_data` decoding for the `crud.Error`.

The `operation_data` type is determined as `rowType` in `crud.Result`.

Also, according to [1], an error can contain one of the following:
- an error
- an array of errors
- nil

So the error decoding logic has been modified to consider each case, in order to avoid comparing an error to nil.

1. https://github.com/tarantool/crud/tree/master#api

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)

Closes #330

### CODE REVIEW

File: crud/example_test.go [hunk 1]
```diff
@@ -78,6 +78,43 @@ func ExampleResult_rowsCustomType() {
...
+	})
+
+	type Tuple struct {
+		_msgpack struct{} `msgpack:",asArray"` //nolint: structcheck,unused
+		Id       uint64
+		BucketId uint64
+		Name     string
+	}
+
+	ret := crud.MakeResult(reflect.TypeOf(Tuple{}))
```
Comment (oleg-jukovec) [inline crud/example_test.go:96]: Please, add an example with a default crud.Result{} (without a decoding type).

Comment (askalt) [reply crud/example_test.go:133]: Added.

File: crud/error.go [hunk 2]
```diff
@@ -59,6 +69,20 @@ func (e *Error) DecodeMsgpack(d *msgpack.Decoder) error {
...
+				if err = d.DecodeValue(tuple); err != nil {
+					return err
+				}
+				e.OperationData = tuple.Elem().Interface()
+			} else {
+				var decoded interface{}
+				if err = d.Decode(&decoded); err != nil {
+					return err
+				}
+				e.OperationData = decoded
```
[the remark this answers is not in the document]
Comment (askalt) [reply crud/error.go]: Yes, thanks you!

File: crud/example_test.go (hunk 1 above)
Comment (oleg-jukovec) [reply crud/example_test.go:133]: Let's make examples on the same/similart values and for the same requests (InsertObjectManyRequest), to make it is obvious what the difference is.

Comment (askalt) [reply crud/example_test.go:143]: Sure, done.

**Review by oleg-jukovec — APPROVED** [review]

**Review by DerekBum — APPROVED** [review]
