### PR TITLE
tests: fix flaky_TestConnectionHandlerOpenUpdateClose

### LINKED ISSUE #502: tests: flaky TestConnectionHandlerOpenUpdateClose
```
2025-11-20T15:44:59.9010260Z === RUN   TestConnectionHandlerOpenUpdateClose
2025-11-20T15:44:59.9208910Z 2025/11/20 15:44:59 tarantool: connect to 127.0.0.1:3013 failed: failed to identify: read error: context canceled
2025-11-20T15:44:59.9312900Z     connection_pool_test.go:1138: 
2025-11-20T15:44:59.9564500Z         	Error Trace:	/Users/runner/work/go-tarantool/go-tarantool/tarantool/go-tarantool/pool/connection_pool_test.go:1138
2025-11-20T15:44:59.9567600Z         	Error:      	Expected nil, but got: &errors.errorString{s:"can't find rw instance in pool"}
2025-11-20T15:44:59.9676660Z         	Test:       	TestConnectionHandlerOpenUpdateClose
2025-11-20T15:44:59.9777130Z         	Messages:   	failed to make ro
2025-11-20T15:44:59.9879310Z --- FAIL: TestConnectionHandlerOpenUpdateClose (0.02s)
2025-11-20T15:44:59.9982560Z === RUN   TestConnectionHandlerOpenError
```

### PR DESCRIPTION
**Pull request by babyTsakhes**
tests: fix flaky_TestConnectionHandlerOpenUpdateClose

- Increased the waiting time to milliseconds. 
- Changed the require.Nilf on require.NoError.

Closes #502

### CODE REVIEW

**Comment by babyTsakhes** [comment]
Changes are ready. Please look this.

File: pool/connection_pool_test.go [hunk 1]
```diff
@@ -1115,15 +1115,15 @@ func TestConnectionHandlerOpenUpdateClose(t *testing.T) {
...
 	defer cancel()
 
 	err := test_helpers.SetClusterRO(ctx, makeDialers(poolServers), connOpts, roles)
-	require.Nilf(t, err, "fail to set roles for cluster")
+	require.NoError(t, err, "fail to set roles for cluster")
 
 	h := &testHandler{}
 	poolOpts := pool.Opts{
-		CheckTimeout:      100 * time.Microsecond,
+		CheckTimeout:      100 * time.Millisecond,
```
Comment (oleg-jukovec) [inline pool/connection_pool_test.go]: Does the change required? Or is it enough to just increase the timeout for context?

**Comment by babyTsakhes** [comment]
Okay, I'll take a look.  At the moment, the test is not flaking, but unfortunately, the time reduction is insignificant.
