### PR TITLE
api: block Connect() on failure if Reconnect > 0

### LINKED ISSUE #436: Block `tarantool.Connect()` until a connection is established or the timeout expires if `Reconnect` option set
Currently `tarantool.Connect()` returns a connection if successfully connected to a Tarantool instance, or an error if the connection fails. It also ignores the `Reconnect` option on the first connection. This differs from the behavior of `net.box`, which blocks and attempts to reconnect if the `reconnect_after` option is non-nil. It is suggested that `tarantool.Connect()` block until the context times out or a connection is established.

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch makes Connect() retry connection attempts if opts.Reconnect is greater than 0. The delay between connection attempts is opts.Reconnect. If opts.MaxReconnects > 0 then the maximum number of attempts is equal to it, otherwise the maximum number of attempts is unlimited. Connect() now also blocks until a connection is established, provided context is cancelled or the number of attempts is exhausted.

Closes #436

What has been done? Why? What problem is being solved?

Connect() now handles connection retries on its own. This simplifies connecting to Tarantool instances when there is no guarantee that the connection will be established on the first try.

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [ ] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

Related issues: #436

### CODE REVIEW

File: connection.go [hunk 1]
```diff
@@ -362,8 +368,17 @@ func Connect(ctx context.Context, dialer Dialer, opts Opts) (conn *Connection, e
 
 	conn.cond = sync.NewCond(&conn.mutex)
 
-	if err = conn.createConnection(ctx); err != nil {
-		return nil, err
+	if conn.opts.Reconnect > 0 {
+		conn.mutex.Lock()
```
Comment (oleg-jukovec) [inline connection.go:372]: Please write a comment here about the fact that a mutex is needed here for the simplicity of the `runReconnects` method implementation.

File: connection.go [hunk 2]
```diff
@@ -362,8 +368,17 @@ func Connect(ctx context.Context, dialer Dialer, opts Opts) (conn *Connection, e
...
+		err = conn.runReconnects(ctx)
+		conn.mutex.Unlock()
+		if err != nil {
+			return nil, err
+		}
+	} else {
+		if err = conn.createConnection(ctx); err != nil {
```
Comment (oleg-jukovec) [inline connection.go:379]: We could do a little renaming since we here.
```suggestion
		if err = conn.connect(ctx); err != nil {
```

File: tarantool_test.go [hunk 3]
```diff
@@ -3972,6 +3972,95 @@ func TestConnect_context_cancel(t *testing.T) {
...
 
+func TestConnectIsBlocked(t *testing.T) {
+	const server = "127.0.0.1:3015"
+
+	testDialer := dialer
+	testDialer.Address = server
+
+	ctx, cancel := context.WithTimeout(context.TODO(), 10*time.Second)
+	defer cancel()
+	delay := 2 * time.Second
```
Comment (oleg-jukovec) [inline tarantool_test.go:3983]: Please try to test the code without timers and timeouts. You can implement your own Dialer mock for example.

File: tarantool_test.go [hunk 4]
```diff
@@ -3972,6 +3972,95 @@ func TestConnect_context_cancel(t *testing.T) {
...
+}
+
+func TestConnectIsBlockedUntilContextExpires(t *testing.T) {
+	const server = "127.0.0.1:3015"
+
+	testDialer := dialer
+	testDialer.Address = server
+
+	now := time.Now()
+	delay := 2 * time.Second
```
Comment (oleg-jukovec) [inline tarantool_test.go:4028]: The same.

File: tarantool_test.go [hunk 5]
```diff
@@ -3972,6 +3972,95 @@ func TestConnect_context_cancel(t *testing.T) {
...
+}
+
+func TestConnectIsUnblockedAfterMaxAttempts(t *testing.T) {
+	const server = "127.0.0.1:3015"
+
+	testDialer := dialer
+	testDialer.Address = server
+
+	now := time.Now()
+	ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
```
Comment (oleg-jukovec) [inline tarantool_test.go:4050]: And here.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
Thanks for the patch. Overall the idea is good, but there are a couple of issues with the implementation.

File: connection.go [hunk 6]
```diff
@@ -656,7 +678,7 @@ func (conn *Connection) reconnectImpl(neterr error, c Conn) {
 	if conn.opts.Reconnect > 0 {
 		if c == conn.c {
 			conn.closeConnection(neterr, false)
-			if err := conn.runReconnects(); err != nil {
+			if err := conn.runReconnects(context.TODO()); err != nil {
```
[the remark this answers is not in the document]
Comment (ImeevMA) [reply connection.go]: Thanks, fixed.

File: connection.go [hunk 7]
```diff
@@ -642,7 +661,10 @@ func (conn *Connection) runReconnects() error {
 		reconnects++
 		conn.mutex.Unlock()
 
-		time.Sleep(time.Until(now.Add(conn.opts.Reconnect)))
+		select {
+		case <-ctx.Done():
```
[the remark this answers is not in the document]
Comment (ImeevMA) [reply connection.go:673]: If we do this, the error may be different from the one we would receive by giving expired context to Connect(). The error is defined by dialer. Added a comment.

File: connection.go [hunk 8]
```diff
@@ -616,19 +631,23 @@ func (conn *Connection) getDialTimeout() time.Duration {
...
-func (conn *Connection) runReconnects() error {
+func (conn *Connection) runReconnects(ctx context.Context) error {
 	dialTimeout := conn.getDialTimeout()
 	var reconnects uint
 	var err error
 
 	for conn.opts.MaxReconnects == 0 || reconnects <= conn.opts.MaxReconnects {
-		now := time.Now()
+		t := time.NewTimer(conn.opts.Reconnect)
+		defer t.Stop()
```
[the remark this answers is not in the document]
Comment (ImeevMA) [reply connection.go]: Thanks, fixed.

File: connection.go (hunk 1 above)
Comment (ImeevMA) [reply connection.go:381]: Fixed.

File: tarantool_test.go (hunk 3 above)
Comment (ImeevMA) [reply tarantool_test.go]: The `retry` logic is implemented in `connection.go`, so I don't see a way to remove `Sleep()`. But I removed the `too early` check. Also, since we don't need a properly functioning connection, we can just make our own dialer that returns the connection after some time. Should I do that? I think it would look a bit nicer, but the test would be more complicated.

File: tarantool_test.go (hunk 4 above)
Comment (ImeevMA) [reply tarantool_test.go]: I removed delay and `too early` check.

File: tarantool_test.go (hunk 5 above)
Comment (ImeevMA) [reply tarantool_test.go]: I removed delay and `too early` check. Also I change `MaxReconnects` to 1.

File: connection.go [hunk 9]
```diff
@@ -92,8 +92,14 @@ func (d defaultLogger) Report(event ConnLogKind, conn *Connection, v ...interfac
 	case LogReconnectFailed:
 		reconnects := v[0].(uint)
 		err := v[1].(error)
-		log.Printf("tarantool: reconnect (%d/%d) to %s failed: %s",
-			reconnects, conn.opts.MaxReconnects, conn.Addr(), err)
+		addr := conn.Addr()
+		if addr == nil {
+			log.Printf("tarantool: connect (%d/%d) failed: %s",
+				reconnects, conn.opts.MaxReconnects, err)
+		} else {
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply connection.go:99]: > The address is set by `Conn`, which is created by dialer. Since creation of `Conn` failed, we have no way to fetch address. Note, I made the same change for `LogLastReconnectFailed`.

So we could get Address from Dialer ourselves. Or not?

> but says nothing about connection status. Should the connection become `Closed`?

Sure, if we return an error from tarantool.Connect then a connection should be closed.

> How do you think, is this a bug?

You could fix it, if you want.

File: tarantool_test.go (hunk 3 above)
Comment (oleg-jukovec) [reply tarantool_test.go]: You could implement a tarantool.Dialer mock and register attempts to call Dialer method. This way you can understand how many attempts there were and the time intervals between them.

File: connection.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (ImeevMA) [reply connection.go:99]: > So we could get Address from Dialer ourselves. Or not?

No, we generally don't know how Dialer gives the address to the Conn.
> Sure, if we return an error from tarantool.Connect then a connection should be closed.

Ok, I will fix this.
> You could fix it, if you want.

Ok, I will fix this in another PR.

File: tarantool_test.go (hunk 3 above)
Comment (ImeevMA) [reply tarantool_test.go]: Thanks, fixed.

File: connection.go [hunk 10]
```diff
@@ -616,19 +640,22 @@ func (conn *Connection) getDialTimeout() time.Duration {
...
-
-		ctx, cancel := context.WithTimeout(context.Background(), dialTimeout)
-		err = conn.createConnection(ctx)
+		localCtx, cancel := context.WithTimeout(ctx, dialTimeout)
+		err = conn.connect(localCtx)
 		cancel()
 
 		if err != nil {
+			if ctx.Err() != nil {
+				return err
```
Comment (oleg-jukovec) [inline connection.go:657]: If you don't wrap a context error than it would be more correct:
```suggestion
				return ctx.Err()
```

File: tarantool_test.go [hunk 11]
```diff
@@ -3972,6 +3972,96 @@ func TestConnect_context_cancel(t *testing.T) {
...
+	reconnectOpts.Reconnect = 100 * time.Millisecond
+	reconnectOpts.MaxReconnects = 100
+	conn, err := Connect(ctx, mockDialer, reconnectOpts)
+	if err != nil {
+		t.Fatalf("Connection was not established: %v", err)
+	}
+	conn.Close()
+	if counter < 10 {
+		t.Fatalf("Expected no less than 10, got %d", counter)
+	}
```
Comment (oleg-jukovec) [inline tarantool_test.go:4020]:
```suggestion
	const server = "127.0.0.1:3015"
	testDialer := dialer
	testDialer.Address = server

	inst, err := test_helpers.StartTarantool(test_helpers.StartOpts{
		Dialer:       testDialer,
		InitScript:   "config.lua",
		Listen:       server,
		WaitStart:    100 * time.Millisecond,
		ConnectRetry: 10,
		RetryTimeout: 500 * time.Millisecond,
	})
	defer test_helpers.StopTarantoolWithCleanup(inst)
	if err != nil {
		t.Fatalf("Unable to start Tarantool: %s", err)
	}

	var counter int
	mockDialer := mockSlowDialer{original: testDialer, counter: &counter}
	ctx, cancel := context.WithTimeout(context.TODO(), 10*time.Second)
	defer cancel()

	reconnectOpts := opts
	reconnectOpts.Reconnect = 100 * time.Millisecond
	reconnectOpts.MaxReconnects = 100
	conn, err := Connect(ctx, mockDialer, reconnectOpts)
	if err != nil {
		t.Fatalf("Connection was not established: %v", err)
	}

	conn.Close()

	if counter < 10 {
		t.Fatalf("Expected no less than 10, got %d", counter)
	}
```
Just a code style fixes.

File: tarantool_test.go [hunk 12]
```diff
@@ -3972,6 +3972,96 @@ func TestConnect_context_cancel(t *testing.T) {
...
+	reconnectOpts.Reconnect = 100 * time.Millisecond
+	reconnectOpts.MaxReconnects = 100
+	_, err := Connect(ctx, testDialer, reconnectOpts)
+	if err == nil {
+		t.Fatal("Connection was unexpectedly established.")
+	}
+	exp := "failed to dial: dial tcp 127.0.0.1:3015: i/o timeout"
+	if err.Error() != exp {
+		t.Fatalf("Expected '%s', got '%v'", exp, err)
+	}
```
Comment (oleg-jukovec) [inline tarantool_test.go:4041]:
```suggestion
	const server = "127.0.0.1:3015"

	testDialer := dialer
	testDialer.Address = server

	ctx, cancel := test_helpers.GetConnectContext()
	defer cancel()

	reconnectOpts := opts
	reconnectOpts.Reconnect = 100 * time.Millisecond
	reconnectOpts.MaxReconnects = 100
	_, err := Connect(ctx, testDialer, reconnectOpts)
	if err == nil {
		t.Fatal("Connection was unexpectedly established.")
	}

	exp := "failed to dial: dial tcp 127.0.0.1:3015: i/o timeout"
	if err.Error() != exp {
		t.Fatalf("Expected '%s', got '%v'", exp, err)
	}
```

File: tarantool_test.go [hunk 13]
```diff
@@ -3972,6 +3972,96 @@ func TestConnect_context_cancel(t *testing.T) {
...
+	reconnectOpts.Reconnect = 100 * time.Millisecond
+	reconnectOpts.MaxReconnects = 1
+	_, err := Connect(ctx, testDialer, reconnectOpts)
+	if err == nil {
+		t.Fatal("Connection was unexpectedly established.")
+	}
+	exp := "last reconnect failed"
+	if !strings.Contains(err.Error(), exp) {
+		t.Fatalf("Expected '%s', got '%v'", exp, err)
+	}
```
Comment (oleg-jukovec) [inline tarantool_test.go:4062]:
```suggestion
	const server = "127.0.0.1:3015"

	testDialer := dialer
	testDialer.Address = server

	ctx, cancel := test_helpers.GetConnectContext()
	defer cancel()

	reconnectOpts := opts
	reconnectOpts.Reconnect = 100 * time.Millisecond
	reconnectOpts.MaxReconnects = 1
	_, err := Connect(ctx, testDialer, reconnectOpts)
	if err == nil {
		t.Fatal("Connection was unexpectedly established.")
	}

	exp := "last reconnect failed"
	if !strings.Contains(err.Error(), exp) {
		t.Fatalf("Expected '%s', got '%v'", exp, err)
	}
```

**Review by oleg-jukovec — COMMENTED** [review]
I have a few non-critical comments.

File: connection.go (hunk 10 above)
Comment (ImeevMA) [reply connection.go:657]: This actually breaks the test (`TestConnect_context_cancel`). I suggest leaving the error we got from the dialer since we don't know the error the dialer will return due to the context being cancelled. Or we can change the checked error in the mentioned test.

Comment (oleg-jukovec) [reply connection.go:657]: To be honest, this is a very strange construction. Please add a comment then.

Comment (ImeevMA) [reply connection.go:665]: I agree. Maybe it would be better to change the test. For now I've added a comment.

File: tarantool_test.go (hunk 11 above)
Comment (ImeevMA) [reply tarantool_test.go]: Thanks, fixed.

File: tarantool_test.go (hunk 12 above)
Comment (ImeevMA) [reply tarantool_test.go]: Thanks, fixed.

File: tarantool_test.go [hunk 14]
```diff
@@ -3972,6 +3972,104 @@ func TestConnect_context_cancel(t *testing.T) {
...
+	reconnectOpts.MaxReconnects = 100
+	_, err := Connect(ctx, testDialer, reconnectOpts)
+	if err == nil {
+		t.Fatal("Connection was unexpectedly established.")
+	}
+
+	exp := "failed to dial: dial tcp 127.0.0.1:3015: i/o timeout"
+	if err.Error() != exp {
+		t.Fatalf("Expected '%s', got '%v'", exp, err)
+	}
```
Comment (patapenka-alexey) [inline tarantool_test.go:4047]:
```suggestion
	assert.EqualError(t, err, exp)
```
Maybe we can use this? And in all other places

Comment (ImeevMA) [reply tarantool_test.go]: Fixed:
<details>

```diff
diff --git a/tarantool_test.go b/tarantool_test.go
index 741e0a4..6a44dc7 100644
--- a/tarantool_test.go
+++ b/tarantool_test.go
@@ -4013,15 +4013,9 @@ func TestConnectIsBlocked(t *testing.T) {
        reconnectOpts.Reconnect = 100 * time.Millisecond
        reconnectOpts.MaxReconnects = 100
        conn, err := Connect(ctx, mockDialer, reconnectOpts)
-       if err != nil {
-               t.Fatalf("Connection was not established: %v", err)
-       }
-
-       conn.Close()
-
-       if counter < 10 {
-               t.Fatalf("Expected no less than 10, got %d", counter)
-       }
+       defer conn.Close()
+       assert.Nil(t, err)
+       assert.GreaterOrEqual(t, counter, 10)
 }
 
 func TestConnectIsBlockedUntilContextExpires(t *testing.T) {
@@ -4037,14 +4031,8 @@ func TestConnectIsBlockedUntilContextExpires(t *testing.T) {
        reconnectOpts.Reconnect = 100 * time.Millisecond
        reconnectOpts.MaxReconnects = 100
        _, err := Connect(ctx, testDialer, reconnectOpts)
-       if err == nil {
-               t.Fatal("Connection was unexpectedly established.")
-       }
-
-       exp := "failed to dial: dial tcp 127.0.0.1:3015: i/o timeout"
-       if err.Error() != exp {
-               t.Fatalf("Expected '%s', got '%v'", exp, err)
-       }
+       assert.NotNil(t, err)
+       assert.ErrorContains(t, err, "failed to dial: dial tcp 127.0.0.1:3015: i/o timeout")
 }
 
 func TestConnectIsUnblockedAfterMaxAttempts(t *testing.T) {
@@ -4060,14 +4048,8 @@ func TestConnectIsUnblockedAfterMaxAttempts(t *testing.T) {
        reconnectOpts.Reconnect = 100 * time.Millisecond
        reconnectOpts.MaxReconnects = 1
        _, err := Connect(ctx, testDialer, reconnectOpts)
-       if err == nil {
-               t.Fatal("Connection was unexpectedly established.")
-       }
-
-       exp := "last reconnect failed"
-       if !strings.Contains(err.Error(), exp) {
-               t.Fatalf("Expected '%s', got '%v'", exp, err)
-       }
+       assert.NotNil(t, err)
+       assert.ErrorContains(t, err, "last reconnect failed")
 }
 
```
</details>

**Review by patapenka-alexey — APPROVED** [review]
LGTM!
