### PR TITLE
box: box.New returns an error instead of panic

### LINKED ISSUE #448: v3: box.New should return an error instead of panic
In user-facing libraries, it's better to fail early with a clearer error message, rather than "invalid memory address or nil pointer dereference". While avoiding panics entirely in third-party libraries is ideal, since we can't break compatibility, this should be implemented in v3.

For example:
```
func New(conn tarantool.Doer) *Box {
	if conn == nil {
		// Check if the provided Tarantool connection is nil, and if it is, panic with an error
		// message. panic early helps to catch and fix nil pointer issues in the code.
		panic("tarantool connection cannot be nil")
	}

	return &Box{
		conn: conn, // Assigns the provided Tarantool connection.
	}
}

```
should be
```
func New(conn tarantool.Doer) (*Box, error) {
	if conn == nil {
		// Check if the provided Tarantool connection is nil, and if it is, panic with an error
		// message. panic early helps to catch and fix nil pointer issues in the code.
		return errors.New("tarantool connection cannot be nil")
	}

	return &Box{
		conn: conn, // Assigns the provided Tarantool connection.
	}, nil
}

func MustNew(conn tarantool.Doer) *Box {
	return utils.Must(New(conn))
}
```

### PR DESCRIPTION
**Pull request by laines-it**
Method `box.New` now returns `(*Box, error)`, because avoiding panics entirely in third-party libraries is ideal, since we can't break compatibility.
Nonetheless, there is still a way to panic on error, via implemented `box.MustNew` wrapper.

I didn't forget about (remove if it is not applicable):

- [X] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [X] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [ ] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

Closes #448

### CODE REVIEW

File: box/tarantool_test.go [hunk 1]
```diff
@@ -83,7 +90,8 @@ func TestBox_Sugar_Schema_UserCreate_NoError(t *testing.T) {
 	conn, err := tarantool.Connect(ctx, dialer, tarantool.Opts{})
 	require.NoError(t, err)
 
-	b := box.New(conn)
+	b, err := box.New(conn)
+	require.NoError(t, err)
```
Comment (oleg-jukovec) [inline box/tarantool_test.go]: It looks like we could replace box.New with box.MustNew in our tests to avoid the error check. In that case we need additional tests that New creates a workable object based on a passed connection.
```suggestion
	b, err := box.MustNew(conn)
```

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
A commit message should be well-formatted too:

50 chars max for a title line.
72 chars max for a message line.
 
```
box: box.New returns an error instead of panic

Method `box.New` now returns (*Box, error), because avoiding panics
entirely in third-party libraries is ideal, since we can't break
compatibility

Nonetheless, there is still a way to panic on error, via implemented
`box.MustNew` wrapper.

Closes #448
```

See:

https://www.tarantool.io/en/doc/latest/contributing/developer_guidelines/#how-to-write-a-commit-message

File: box/box_test.go [hunk 2]
```diff
@@ -15,8 +15,15 @@ import (
 func TestNew(t *testing.T) {
 	t.Parallel()
 
+	_, err := box.New(nil)
+	require.Error(t, err)
+}
+
+func TestMustNew(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (laines-it) [reply box/box_test.go]: When we use MustNew in other test with mock connection (e.g. TestMocked_), and this test passes, do we still need to check MustNew can return workable object? If yes, what is the criteria of "workablility" for valid connection?

File: CHANGELOG.md [hunk 3]
```diff
@@ -11,13 +11,16 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
...
+* Added `box.MustNew` wrapper for `box.New` without an error (#448).
 
 ### Changed
 
 * Required Go version is `1.24` now (#456).
+* `box.New` returns an error instead of panic (#448).
 
 ### Fixed
 
+
```
Comment (oleg-jukovec) [inline CHANGELOG.md]: Please, revert the unnecessary change.

```suggestion
```
