### PR TITLE
api: queue works with connection_pool

### LINKED ISSUE #176: Make queue works with connection_pool
For now we cannot work with queue on replicaset setups:

```go
package main

import (
    "fmt"
    "time"

    "github.com/tarantool/go-tarantool"
    "github.com/tarantool/go-tarantool/connection_pool"
    "github.com/tarantool/go-tarantool/queue"
)

func main() {
    replicaset, err := connection_pool.Connect([]string{"127.0.0.1:3301", "127.0.0.1:3302"}, tarantool.Opts{
        Timeout: 500 * time.Millisecond,
    })
    if err != nil {
        fmt.Printf("error in connect is %v", err)
    }
    
    defer replicaset.Close()
    
    q := queue.New(replicaset, "test_tube_tmp2")
    stat, err := q.Statistic()
    fmt.Println(stat)
}
```

This code will fails:
```
$ go run test.go
# command-line-arguments
./test.go:25:17: cannot use replicaset (variable of type *connection_pool.ConnectionPool) as type tarantool.Connector in argument to queue.New:
	*connection_pool.ConnectionPool does not implement tarantool.Connector (wrong type for Call method)
		have Call(functionName string, args interface{}, userMode connection_pool.Mode) (resp *tarantool.Response, err error)
		want Call(functionName string, args interface{}) (resp *tarantool.Response, err error)
```

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The patchet allows to use the queue subpackage with the connection_pool subpackage:

1. It adds missed `Execute*` methods to ConnectionPool.
2. It adds ConnectorAdaptor to the connection_pool subpackage to be able to use ConnectionPool as Connector.

Finally, it adds an example how-to use a Queue with ConnectionPool.

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [x] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

Related issues:

Closes #176

### CODE REVIEW

**Comment by oleg-jukovec** [comment]
This pull request is generally ready for review, but I'll wait for #210

Also there is a bug in the queue that needs to be fixed in for the tests to make tests successful.
https://github.com/tarantool/queue/issues/185

**Comment by oleg-jukovec** [comment]
There is a problem with download from tarantool.io, so we have 2.x-latest tests failed:
```
2022-09-12T13:08:26.7307211Z ##[group]Run curl -L https://tarantool.io/pre-release/2/installer.sh | sudo bash
2022-09-12T13:08:26.7307719Z [36;1mcurl -L https://tarantool.io/pre-release/2/installer.sh | sudo bash[0m
2022-09-12T13:08:26.7308061Z [36;1msudo apt install -y tarantool tarantool-dev[0m
2022-09-12T13:08:26.7365945Z shell: /usr/bin/bash -e {0}
2022-09-12T13:08:26.7366196Z ##[endgroup]
2022-09-12T13:08:26.7606388Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-09-12T13:08:26.7608586Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-09-12T13:08:26.7608776Z 
2022-09-12T13:08:27.3371045Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-09-12T13:08:27.3414516Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-09-12T13:08:27.3415325Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-09-12T13:08:27.3420023Z curl: (60) SSL certificate problem: certificate has expired
2022-09-12T13:08:27.3420600Z More details here: https://curl.haxx.se/docs/sslcerts.html
```
I think we can ignore this problem for a couple of days.

File: connection_pool/connector_test.go [hunk 1]
```diff
@@ -0,0 +1,1168 @@
+package connection_pool_test
```
Comment (DifferentialOrange) [inline connection_pool/connector_test.go:1]: Was the test built from scratch or was it based on some existing test suite?

File: connection_pool/connector_test.go [hunk 2]
```diff
@@ -0,0 +1,1168 @@
...
+	m := &doMock{}
+	c := NewConnectorAdapter(m, testMode)
+
+	fut := c.Do(reqRequest)
+
+	require.Equalf(t, reqFuture, fut, "unexpected future")
+	require.Equalf(t, 1, m.called, "should be called only once")
+	require.Equalf(t, reqRequest, m.req, "unexpected request")
+	require.Equalf(t, testMode, m.mode, "unexpected proxy mode")
+}
```
Comment (DifferentialOrange) [inline connection_pool/connector_test.go:1168]: I think it would be nice to have an example too.

File: connection_pool/connection_pool.go [hunk 3]
```diff
@@ -98,6 +98,7 @@ type ConnectionPool struct {
 	anyPool    *RoundRobinStrategy
 	poolsMutex sync.RWMutex
 }
+
```
Comment (DifferentialOrange) [inline connection_pool/connection_pool.go:101]: It seems like it should be in another commit.

File: queue/queue_test.go [hunk 4]
```diff
@@ -14,6 +14,14 @@ import (
 )
 
 var server = "127.0.0.1:3013"
+var serversPool = []string{
```
Comment (DifferentialOrange) [inline queue/queue_test.go:17]: I see pool setup but don't see any tests with it.

File: queue/example_connection_pool_test.go [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+func (h *QueueConnectionHandler) Deactivated(conn *tarantool.Connection,
+	role connection_pool.Role) error {
+	return nil
+}
+
+// Example demonstrates how to use the queue package with the connection_pool
+// package. First of all, you need to create a connection handler for the
+// a ConnectionPool object to process new connections from RW-instances.
+//
+// You need to registry a shared session UUID at a first master connection.
```
Comment (DifferentialOrange) [inline queue/example_connection_pool_test.go:85]: register*

File: queue/example_connection_pool_test.go [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+// It needs to be used to re-identify as the shared session on new
+// RW-instances. See QueueConnectionHandler.Discovered() implementation.
+//
+// After that, you need to create a ConnectorAdapter object with RW mode for
+// the ConnectionPool to send requests into RW-instances. This adapter can
+// be used to create a ready-to-work queue object.
+func Example_connectionPool() {
```
Comment (DifferentialOrange) [inline queue/example_connection_pool_test.go:92]: Why it is an example and not some API method that user can call in one line? May user want to change some parts of the example?

File: queue/example_connection_pool_test.go [hunk 7]
```diff
@@ -0,0 +1,148 @@
...
+
+	if task, err := q.Take(); err != nil {
+		log.Fatalf("unable to take data from the queue: %s", err)
+	} else {
+		task.Ack()
+		fmt.Println("data:", task.Data())
+	}
+	// Output:
+	// A Queue object is ready to work.
+	// data: test_data
```
Comment (DifferentialOrange) [inline queue/example_connection_pool_test.go:147]: It would be nice to have some example that checks up a case with master switch.

**Review by DifferentialOrange — COMMENTED** [review]
Thank you for your patch!

I have lest several questions. Most of them are not of a great importance, except for the lack of test for the main feature. (Maybe I had missed something.)

File: CHANGELOG.md [hunk 8]
```diff
@@ -13,6 +13,7 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
 - Support queue 1.2.0 (#177)
 - ConnectionHandler interface for handling changes of connections in
   ConnectionPool (#178)
+- Execute, ExecuteTyped and ExecuteAsync methods to ConnectionPool (#176)
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply CHANGELOG.md:16]: Well... without this, we cannot make a pull request in the current form (implement ConnectorAdapter).

[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply CHANGELOG.md:16]: Yes, it is.

File: connection_pool/connection_pool.go [hunk 9]
```diff
@@ -98,6 +98,7 @@ type ConnectionPool struct {
 	anyPool    *RoundRobinStrategy
 	poolsMutex sync.RWMutex
 }
+var _ Pooler = (*ConnectionPool)(nil)
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply connection_pool/connection_pool.go:102]: Yes, it is.

File: connection_pool/connector_test.go (hunk 1 above)
Comment (oleg-jukovec) [reply connection_pool/connector_test.go:1]: No, it was done by my hands.

File: queue/queue_test.go (hunk 4 above)
Comment (oleg-jukovec) [reply queue/queue_test.go:17]: The pool used by queue/example_connection_pool_test.go

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:147]: It is not a trivial task. We don't have example how to switch a master in the replicaset (and replicaset configuration too =) connection_pool in tests are just unlinked instances), this may complicate the example too much (and its essence will be lost).

But I can try.

File: queue/example_connection_pool_test.go (hunk 6 above)
Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:92]: ConnectionPool has much more use cases (master-master as example, just instances without a replicaset). I think it is impossible to provide a universal API here.

File: connection_pool/connector_test.go (hunk 2 above)
Comment (oleg-jukovec) [reply connection_pool/connector_test.go:1168]: I've added ExampleConnectorAdapter.

File: connection_pool/connection_pool.go (hunk 3 above)
Comment (oleg-jukovec) [reply connection_pool/connection_pool.go:101]: Thank you, fixed.

File: CHANGELOG.md (hunk 8 above)
[the remark this answers is not in the document]
Comment (DifferentialOrange) [reply CHANGELOG.md:16]: Ok, that's fair

File: queue/example_connection_pool_test.go (hunk 6 above)
Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:92]: Does queue support master-master?

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:147]: > and its essence will be lost

Isn't the essence of connection pool is to provide a way to work with cluster (replicaset) disregarding of what state it has?

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:147]: The connection pool does not have failover or replicaset logic itself. So the code will be in the example. It will make it much more difficult.

File: queue/example_connection_pool_test.go (hunk 6 above)
Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:92]: It looks like it doesn't, at least I haven't seen any collision protection.

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:147]: Does it at least work manually? Or this example doesn't support failover?

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:147]: It works manually =)

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:147]: Well, ok, let it be.

**Review by DifferentialOrange — APPROVED** [review]

File: queue/example_connection_pool_test.go [hunk 10]
```diff
@@ -0,0 +1,148 @@
...
+				h.err = q.Create(h.cfg)
+			}
+		}
+		h.registered = h.err == nil
+		close(h.done)
+		h.registerMutex.Unlock()
+		return h.err
+	} else {
+		// We already registered. We don't need the lock any more.
+		h.registerMutex.Unlock()
```
Comment (DifferentialOrange) [inline queue/example_connection_pool_test.go:65]: Isn't it all equivalent to `defer h.registerMutex.Unlock()`?

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:65]: No, the code unlocks the mutex immediately. Defer at the end of a function.

The idea here: we don't need to hold the lock in re-identify case because we already have a valid session UUID.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:65]: Are concurrent `Identifiy`es and `Create`s valid?

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:65]: No, they are not.

We check `h.registered` value under the lock, it may become `true` only under the lock too. So if h.registered == true then `Create` already done.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:65]: No, they're under the lock
```go
h.registerMutex.Unlock()
if _, err := q.Identify(&h.uuid); err != nil {
        return err
}
if err := q.Create(h.cfg); err != nil {
        return err
}
```

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:147]: I've tried to run the example and check if switchover works and, well, it doesn't seems like it is:
```
=== RUN   Example_connectionPool
2022/09/20 13:37:22 tarantool: storing connection to 127.0.0.1:3015 canceled: .../.rocks/share/tarantool/queue/abstract/queue_session.lua:223: The UUID 6828cabe-9471-4b56-b99a-35f326c223ee is unknown. (0x20)
2022/09/20 13:37:23 tarantool: storing connection to 127.0.0.1:3015 canceled: .../.rocks/share/tarantool/queue/abstract/queue_session.lua:223: The UUID 6828cabe-9471-4b56-b99a-35f326c223ee is unknown. (0x20)
2022/09/20 13:37:52 unable to take data from the queue: can't find rw instance in pool
FAIL	github.com/tarantool/go-tarantool/queue	122.469s
FAIL
```

It's most likely that I had misconfigured something (I messed with `queue/config.lua` to setup replication -- and, to be honest, it wasn't an easy task), but it is a bad signal: if user really want to work with queue, he need to take the example and complete it so it would really be useful. Because example in its current form is not so useful: it demonstrates how to work with single node queue with connection pool (which is a bit weird).

So, once again, I want to raise a question about having a proper test (at least in the form of an example).

**Review by DifferentialOrange — CHANGES_REQUESTED** [review]
Sorry, it doesn't seems nice to remove the approval (especially since nothing had changed since last revision), but I've tried to manually run the examples and it wasn't an immediate success.

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:147]: The example is how to use queue subpackage with a connection_pool subpackage.

It is not about ConnectionPool configuration or replicaset configuration or failover configuration. It is just:

1. Set up Connection handlers for ConnectionPool.
2. Use ConnectionPool.ConnectorAdapter().
3. Use the adapter for a queue.

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:170]: I've added a sample files for manual play with the code. Please, see an update.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > The example is how to use queue subpackage with a connection_pool subpackage.

Such example is useless if the only thing it does is work with single-node queue.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > I've added a sample files for manual play with the code. Please, see an update.

It should be easy to switch instance ro state -- just a simple eval. So the only thing we need to implement for real example is to configure pool as replicaset. Since you're already have a draft of `config.lua`, a part of work is done. I don't think it would be too time-consuming.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: And if it won't be enough to provide an example with switchover, it means that this example is not a good example of working with queue replicaset (since connection_pool is designed to work with replicaset) and user won't be able to use it.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > The example shows just how a user may to connect a `queue` with a `connection_pool`.

It would be nice to have an example which user can build its logic on. And by "build its logic on" I don't mean implementing handles for basic behavior like failover.

If a new user would want to work with fail-tolerant queue based on Tarantool from Go, I assume that he won't be able to do it unless he spend a lot of time studying both Tarantool and go-tarantool. The main reason I think so is because I couldn't do it myself in short span of time (and I have both Tarantool and go-tarantool experience before) and I don't think that starting a full-fledged debug cycle is a good feature of an example.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: And, well, it still isn't nice to don't have a test of a feature if the feature is complicated. And this one is complicated. I'm okay of using example as a test since it is a test in some way (`go test` runs it and checks its output), but I not support ignoring integration test since tarantool/queue never will have one with go-tarantool too.

File: queue/example_connection_pool_test.go (hunk 10 above)
Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:65]: So it still sounds like that unlock is dangerous.

File: queue/example_connection_pool_test.go (hunk 7 above)
Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:170]: > since connection_pool is designed to work with replicaset

It actually does not. It is designed to work with a set of instances. It does have any logic to work with replicaset.

It can not start an instance, it can not configure an instance, it can not change a role of an intance. The repository is a connector, we provide basic blocks for a feature implementation.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: When we've discussed with Product team the idea of connection pools, in result we've came to a conclusion that it must be able to work with replicaset. Working with vshard cluster is bothersome and rather useless since you can (and should) just implement procedures on vshard router. By using connection pool, you may use the same API as in a single node connection, but with fault-tolerant replicaset underneath. While working with data, it makes any sense only in case when write and read operations results are the same. Otherwise, you'll need to play Russian Roulette (considering underlying round-robin nature) with `get(key)` until you find an instance that contains a record with key. `connection_pool` with plain set of unrelated instances is useless in most real cases.

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:170]: >  but I not support ignoring integration test since tarantool/queue never will have one with go-tarantool too.

What is the idea of your integration test? What do you propose to test? Complex tasks can be splitted into subtasks.

1. We don't need the `ConnectionPool` to check is the `Queue` could work on a new master instance.
2. We don't need the `Queue` to check is the `ConnectionPool` handles connection properly (we already have such tests).
3. We even don't need the `ConnectionPool` to test the handlers code of the example.

Comment (oleg-jukovec) [reply queue/example_connection_pool_test.go:170]: > If a new user would want to work with fault-tolerant queue based on Tarantool from Go, I assume that he won't be able to do it unless he spend a lot of time studying both Tarantool and go-tarantool. The main reason I think so is because I couldn't do it myself in short span of time (and I have both Tarantool and go-tarantool experience before) and I don't think that starting a full-fledged debug cycle is a good feature of an example.

It depends on what we want to see from the connector: universal building blocks or the implementation of some behavior. 
The current example just shows one of the ways to connect the building blocks. No more than that. I didn't envisage it as only possible one way of the connection.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > What is an idea of your integration test? What do you propose to test? Complex tasks can be splitted into subtasks.

1. We connect to a queue replicaset.
2. User takes a task.
3. Master had switched
4. User acknowledges a task.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > Complex tasks can be splitted into subtasks.

It sounds like a case when one forgets to write an integration test because they already have unit tests.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: I believe that everything is work separately. But it is tricky to take these bricks and make them work together. When I took existing example and tried to work with queue replicaset (and I had seen that example sets up queue cfg to work with replicaset), it didn't worked out.

This PR claims that queue work with connection pool. If connection pool is an unrelated set of instances, one may work with queue in it only as a single node connection_pool, which is rather absurd. It is expected (at least from me, and I don't think I'm the only one) that queue replicaset works with connection pool.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: > It depends on what we want to see from the connector: universal building blocks or the implementation of some behavior. 

User could built queue with connection pool even before this PR, if he really wanted to. ConnectionAdapter made this quest a bit easier. Since we've introduced ConnectionAdapter building block, we need some example on how one should work with it. And we're already have an idea of such example: work with queue replicaset. It's mostly because of this example we have introduced https://github.com/tarantool/go-tarantool/pull/210 and https://github.com/tarantool/go-tarantool/pull/206 . And this PR should finish the story. 

> The current example just shows a one way to connect the building blocks. No more than that. I didn't envisage it as only possible way of the connection.

Failover is a basic behavior. If someone wouldn't want it, he just may ignore the example.

We either show user how to work with queue replicaset or we don't. And if we show, it better be reproducible.

Comment (DifferentialOrange) [reply queue/example_connection_pool_test.go:170]: This discussion takes more time than needed to actually finish the test.

**Comment by oleg-jukovec** [comment]
> Sorry, it doesn't seems nice to remove the approval (especially since nothing had changed since last revision), but I've tried to manually run the examples and it wasn't an immediate success.

I have updated the example connection_pool + queue. Let's have another round of review.

**Comment by DifferentialOrange** [comment]
Sorry, I don't get how force-pulling the branch had resulted in its deleting on the remote.

**Review by DifferentialOrange — APPROVED** [review]
Thank you, seems awesome.

I've also tried to ack the taken task after one more master switch. If you want, you may add it too, see `git diff` below.

```diff
diff --git a/queue/example_connection_pool_test.go b/queue/example_connection_pool_test.go
index bf1d53d..7b4deae 100644
--- a/queue/example_connection_pool_test.go
+++ b/queue/example_connection_pool_test.go
@@ -185,17 +185,50 @@ func Example_connectionPool() {
        }
 
        // Take a data from the new master instance.
-       if task, err := q.Take(); err == nil || task.Data() == nil {
-               task.Ack()
+       var task *queue.Task
+       task, err = q.Take()
+       if err == nil || task.Data() == nil {
                fmt.Println("Got data:", task.Data())
        } else {
                fmt.Println("Unable to got data:", err)
        }
 
+       // Switch a master instance in the pool.
+       roles = []bool{false, true}
+       err = test_helpers.SetClusterRO(servers, connOpts, roles)
+       if err != nil {
+               fmt.Printf("Unable to set cluster roles: %s", err)
+               return
+       }
+
+       // Wait for a new master instance re-identification.
+       <-h.masterUpdated
+       if h.err != nil {
+               fmt.Printf("Unable to re-identify in the pool: %s", h.err)
+               return
+       }
+
+       err = task.Ack()
+
+       if err != nil {
+               fmt.Printf("Unable to ack the task: %s", err)
+               return
+       }
+
+       var stats interface{}
+       stats, err = q.Statistic()
+       if err != nil {
+               fmt.Printf("Unable to get stats: %s", err)
+               return
+       }
+       fmt.Println(stats)
+
        // Output:
        // Master 127.0.0.1:3014 is ready to work!
        // A Queue object is ready to work.
        // Send data: test_data
        // Master 127.0.0.1:3014 is ready to work!
        // A Queue object is ready to work.
        // Send data: test_data
        // Master 127.0.0.1:3015 is ready to work!
        // Got data: test_data
+       // Master 127.0.0.1:3014 is ready to work!
+       // map[calls:map[ack:1 bury:0 delay:0 delete:0 kick:0 put:1 release:0 take:0 touch:0 ttl:0 ttr:0] tasks:map[buried:0 delayed:0 done:1 ready:0 taken:0 total:0]]
 }
```

**Review by vr009 — APPROVED** [review]
LGTM
