### PR TITLE
bugfix: flaky TestClientRequestObjectsWithContext 

### LINKED ISSUE #244: Flaky TestClientIdRequestObjectWithContext
```
2022-12-05T10:18:16.0993007Z === RUN   TestClientIdRequestObjectWithContext
2022-12-05T10:18:16.1012546Z --- FAIL: TestClientIdRequestObjectWithContext (0.00s)
2022-12-05T10:18:16.1012900Z     tarantool_test.go:2989: 
2022-12-05T10:18:16.1013296Z         	Error Trace:	tarantool_test.go:2989
2022-12-05T10:18:16.1016919Z         	Error:      	Expected nil, but got: &tarantool.Response{RequestId:0x3, Code:0x30, Error:"Unknown request type 73", Data:[]interface {}(nil), MetaData:[]tarantool.ColumnMetaData(nil), SQLInfo:tarantool.SQLInfo{AffectedCount:0x0, InfoAutoincrementIds:[]uint64(nil)}, buf:tarantool.smallBuf{b:[]uint8{0x83, 0x0, 0xce, 0x0, 0x0, 0x80, 0x30, 0x1, 0xcf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3, 0x5, 0xce, 0x0, 0x0, 0x0, 0x69, 0x82, 0x31, 0xb7, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x20, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x20, 0x74, 0x79, 0x70, 0x65, 0x20, 0x37, 0x33, 0x52, 0x81, 0x0, 0x91, 0x86, 0x0, 0xab, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2, 0xcd, 0x5, 0x22, 0x1, 0xd9, 0x2c, 0x2f, 0x5f, 0x5f, 0x77, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x6f, 0x6f, 0x6c, 0x2d, 0x32, 0x2e, 0x38, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x62, 0x6f, 0x78, 0x2f, 0x69, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x63, 0x3, 0xb7, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x20, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x20, 0x74, 0x79, 0x70, 0x65, 0x20, 0x37, 0x33, 0x4, 0x0, 0x5, 0x30}, p:23}}
2022-12-05T10:18:16.1018509Z         	Test:       	TestClientIdRequestObjectWithContext
2022-12-05T10:18:16.1018887Z         	Messages:   	Response is empty
```

https://github.com/tarantool/go-tarantool/actions/runs/3618947238/jobs/6099414757

### PR DESCRIPTION
**Pull request by oleg-jukovec**
The patch makes the test more deterministic. It helps to avoid
canceling a request with an already received response.

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)

Related issues:

Closes #244

### CODE REVIEW

File: connection.go [hunk 1]
```diff
@@ -1310,15 +1304,6 @@ func (conn *Connection) Do(req Request) *Future {
...
 	}
-	if req.Ctx() != nil {
-		select {
-		case <-req.Ctx().Done():
-			fut := NewFuture()
-			fut.SetError(fmt.Errorf("context is done"))
-			return fut
-		default:
-		}
-	}
```
Comment (vr009) [inline connection.go:1321]: You haven't described, why this deletion?

File: connection.go [hunk 2]
```diff
@@ -1062,22 +1062,18 @@ func (conn *Connection) newFuture(ctx context.Context) (fut *Future) {
...
-		select {
-		case <-ctx.Done():
-			conn.cancelFuture(fut, fmt.Errorf("context is done"))
-		default:
-			select {
-			case <-fut.done:
-			case <-ctx.Done():
-				conn.cancelFuture(fut, fmt.Errorf("context is done"))
-			}
-		}
```
Comment (vr009) [inline connection.go:1080]: As you know, go doesn't ensure that if you have both channels done, the first in the select will be chosen. The given construction provides it. Also, this optimization allows us not to lock a mutex ahead of time. Are you sure of this change?

File: connection.go (hunk 1 above)
Comment (oleg-jukovec) [reply connection.go:1321]: This is just a simplification of an optional check.

See the commit:

[code health: simplify context checks](https://github.com/tarantool/go-tarantool/pull/253/commits/091b93873ad1f99a55cdf357ce4213b4828b46b1)

We don't need to over-optimize the work with requests with contexts
that already done. It doesn't look like a work method. It is better
to simplify the code.

Part of https://github.com/tarantool/go-tarantool/issues/244

Comment (vr009) [reply connection.go:1321]: But this way we avoided a putting a new request into the queue and starting a watchdog extra?

File: connection.go (hunk 2 above)
Comment (oleg-jukovec) [reply connection.go:1080]: > As you know, golang doesn't ensure that if you have both channels done, the first one in the select will be chosen. The given construction provides it.

1. The ordering is saved:

```Go
func (conn *Connection) contextWatchdog(fut *Future, ctx context.Context) {
        // Wait.
	select {
	case <-fut.done:
	case <-ctx.Done():
	}

        // Ordering.
	select {
	case <-fut.done:
		return
	default:
		conn.cancelFuture(fut, fmt.Errorf("context is done"))
	}
}
```

2. In fact it does not provide ordering in the old code:

```Go
			select {
			case <-fut.done:
			case <-ctx.Done():
				conn.cancelFuture(fut, fmt.Errorf("context is done"))
			}
```

> Also, this optimization allows us not to lock a mutex ahead of time. Are you sure of this change?

We're likely to have a lock here anyway (we just check req.Ctx().Done() and just send a request). So the optimization will not be helpful in this case.

File: connection.go (hunk 1 above)
Comment (oleg-jukovec) [reply connection.go:1321]: We do not send a request in this case and don't start a watchdog at now too (because we have the same check after newFuture() and before putFuture()).

In fact, we were avoiding an unnecessary `newFuture` call with the check. But it doesn't look like too big problem: l assume that at a usual usecase a context does not done here.

File: connection.go (hunk 2 above)
Comment (vr009) [reply connection.go:1080]: Thank you for explanation.

File: connection.go (hunk 1 above)
Comment (vr009) [reply connection.go:1321]: Ok, thank you for explanation.

File: connection.go (hunk 2 above)
Comment (vr009) [reply connection.go:1080]: Well it seems, that the first two check will never be successful unless we pass an already done (or near that) context, so let us leave your version.

**Review by vr009 — APPROVED** [review]

**Review by GRISHNOV — APPROVED** [review]
