### PR TITLE
api: add context to connection create

### LINKED ISSUE #136: v2: restart on connection create
I've tried to use reconnect to wait for `tarantool` started with Go to bootstrap, but it doesn't work.

### init.lua

```lua
box.cfg{}
box.schema.user.grant('guest', 'execute', 'universe', nil, { if_not_exists = true })
box.cfg{ listen = 3301 }
```

### main.go

```go
package main

import (
	"log"
	"os/exec"
	"time"

	"github.com/tarantool/go-tarantool"
)

func main() {
	// Prepare tarantool command
	cmd := exec.Command("tarantool", "init.lua")

	// Start tarantool.
	err := cmd.Start()
	if err != nil {
		log.Panic("Failed to start: ", err)
	}
	defer cmd.Process.Kill()

	// Uncomment to wait explicitly.
	// time.Sleep(200 * time.Millisecond)

	// Try to connect and ping tarantool.
	var opts = tarantool.Opts{
		Timeout:       500 * time.Millisecond,
		User:          "guest",
		Pass:          "",
		MaxReconnects: 5,
		Reconnect:     200 * time.Millisecond,
		SkipSchema:    true,
	}

	conn, cerr := tarantool.Connect("127.0.0.1:3301", opts)
	if cerr != nil {
		log.Panic("Failed to connect: ", cerr)
	}
	if conn == nil {
		log.Panic("Conn is nil after connect")
	}
	defer conn.Close()

	resp, rerr := conn.Ping()
	if rerr != nil {
		log.Panic("Failed to ping: ", rerr)
	}
	if resp == nil {
		log.Panic("Response is nil after ping")
	}
}
```

### Run

```bash
go mod init example
go mod tidy
go run .

2022/01/17 13:06:53 Failed to ping: client connection is not ready (0x4000)
panic: Failed to ping: client connection is not ready (0x4000)

goroutine 1 [running]:
log.Panic({0xc00013dec8, 0xbebc200, 0x5})
	/usr/local/go/src/log/log.go:354 +0x65
main.main()
	/home/georgymoiseev/Development/sandbox/goreconnect/main.go:45 +0x313
exit status 2
```

### Run (uncomment time.Sleep)

```bash
go mod init example
go mod tidy
go run .

# ok
```

So either I do it wrong (for example, looks like it shouldn't work without `SkipSchema: true`, but it isn't enough):
https://github.com/tarantool/go-tarantool/blob/9c9a68e09870257cd44bc75da9ffdc829b5e1d19/connection.go#L193-L194
or it is broken.

### PR DESCRIPTION
**Pull request by DerekBum**
`connection.Connect` and `pool.Connect` no longer return non-working connection objects. Those functions now accept context as their first arguments, which user may cancel in process.

`connection.Connect` will block until either the working connection created (and returned), `opts.MaxReconnects` creation attempts were made (returns error) or the context is canceled by user (returns error too).

I didn't forget about (remove if it is not applicable):

- [x] Tests (see [documentation](https://pkg.go.dev/testing) for a testing package)
- [x] Changelog (see [documentation](https://keepachangelog.com/en/1.0.0/) for changelog format)
- [x] Documentation (see [documentation](https://go.dev/blog/godoc) for documentation style guide)

Closes #136

### CODE REVIEW

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
1. I've expect that a `context` could be used with a network connection call. We could use `net.DialContext` instead of `net.Dial`.
2. What do you thing about get rid of the `opts.Reconnect logic` with timeouts and retries inside the `Connect()`? We could use just a `context` object to handle the `Connect` lifetime and try to make the connection only once.

File: pool/connection_pool.go [hunk 1]
```diff
@@ -170,7 +172,7 @@ func ConnectWithOpts(addrs []string, connOpts tarantool.Opts, opts Opts) (*Conne
 	connPool.state.set(connectedState)
 
 	for _, s := range connPool.addrs {
-		go connPool.controller(s)
+		go connPool.controller(ctx, s)
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go:175]: But we call `tryConnect` (calls `Connect`) and `reconnect` from `controller`. Do we need to pass `context.Background` to them?

[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply pool/connection_pool.go:175]: > Do we need to pass `context.Background` to them?

`controller(ctx)` -> `tryConnect(ctx)` should be something more interesting. It would be great to cancel `controller(ctx)` -> `tryConnect(ctx)` with `ConnectionPool.Close()`.

**Comment by DerekBum** [comment]
We are currently using `net.diatTimeout`: https://github.com/tarantool/go-tarantool/blob/d8df65dcd0f29a6a5d07472115cbcf2753b12609/dial.go#L201-L212

I don't think we can use context from `Connect` call in this case (unless we ask the user to use `contextWithTimeout` to specify `DialTimeout` field).

**Comment by oleg-jukovec** [comment]
> DialTimeout

We could remove the `opts.DialTimeout` since we will use a context object that more flexible.

**Comment by DerekBum** [comment]
NB: need to change go.mod and go.sum after the patch from `go-openssl`.

File: connection.go [hunk 2]
```diff
@@ -658,7 +656,8 @@ func pack(h *smallWBuf, enc *msgpack.Encoder, reqid uint32,
 	return
 }
 
-func (conn *Connection) createConnection(reconnect bool) (err error) {
+func (conn *Connection) createConnection(ctx context.Context,
+	reconnect bool) (err error) {
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Updated.

File: tarantool_test.go [hunk 3]
```diff
@@ -4019,6 +4019,47 @@ func TestConnect_schema_update(t *testing.T) {
...
+	var wg sync.WaitGroup
+	wg.Add(1)
+
+	go func() {
+		defer wg.Done()
+		conn, err = Connect(ctx, "err", connLongReconnectOpts)
+	}()
+
+	time.Sleep(5 * time.Second)
+
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply tarantool_test.go]: Updated.

File: pool/connection_pool.go [hunk 4]
```diff
@@ -240,15 +243,15 @@ func (p *ConnectionPool) Add(addr string) error {
...
+	if err := p.tryConnect(ctx, e); err != nil {
 		p.addrsMutex.Lock()
 		delete(p.addrs, addr)
 		p.addrsMutex.Unlock()
 		close(e.closed)
 		return err
 	}
 
-	go p.controller(e)
+	go p.controller(ctx, e)
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go]: Updated.

File: pool/connection_pool_test.go [hunk 5]
```diff
@@ -84,9 +86,52 @@ func TestConnSuccessfully(t *testing.T) {
...
+	wg.Add(1)
+
+	go func() {
+		defer wg.Done()
+
+		connPool, err = pool.Connect(ctx, []string{"err"},
+			connLongReconnectOpts)
+	}()
+
+	time.Sleep(5 * time.Second)
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool_test.go]: Updated.

File: example_test.go [hunk 6]
```diff
@@ -913,12 +913,13 @@ func ExampleFuture_GetIterator() {
 }
 
 func ExampleConnect() {
-	conn, err := tarantool.Connect("127.0.0.1:3013", tarantool.Opts{
-		Timeout:     5 * time.Second,
-		User:        "test",
-		Pass:        "test",
-		Concurrency: 32,
-	})
+	conn, err := tarantool.Connect(context.Background(), "127.0.0.1:3013",
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply example_test.go]: Updated.

File: README.md [hunk 7]
```diff
@@ -105,13 +105,15 @@ about what it does.
...
 import (
+	"context"
 	"fmt"
 	"github.com/tarantool/go-tarantool/v2"
 )
 
 func main() {
 	opts := tarantool.Opts{User: "guest"}
-	conn, err := tarantool.Connect("127.0.0.1:3301", opts)
+	ctx := context.Background()
```
Comment (oleg-jukovec) [inline README.md:115]: Let's use a context with timeout in the example.

File: connection.go [hunk 8]
```diff
@@ -731,7 +728,7 @@ func (conn *Connection) reconnectImpl(neterr error, c Conn) {
 	if conn.opts.Reconnect > 0 {
 		if c == conn.c {
 			conn.closeConnection(neterr, false)
-			if err := conn.createConnection(true); err != nil {
+			if err := conn.createConnection(context.Background(), true); err != nil {
```
Comment (oleg-jukovec) [inline connection.go:731]: We could use a context with timeout here.

File: tarantool_test.go [hunk 9]
```diff
@@ -4019,6 +4019,38 @@ func TestConnect_schema_update(t *testing.T) {
...
+	var wg sync.WaitGroup
+	wg.Add(1)
+
+	go func() {
+		defer wg.Done()
+		cancel()
+		conn, err = Connect(ctx, server, connLongReconnectOpts)
+	}()
+
+	cancel()
```
Comment (oleg-jukovec) [inline tarantool_test.go:4045]: Why do you call cancel() twice? Why we need the goroutine?

File: test_helpers/pool_helper.go [hunk 10]
```diff
@@ -192,7 +193,7 @@ func InsertOnInstances(servers []string, connOpts tarantool.Opts, space interfac
 }
 
 func SetInstanceRO(server string, connOpts tarantool.Opts, isReplica bool) error {
-	conn, err := tarantool.Connect(server, connOpts)
+	conn, err := tarantool.Connect(context.Background(), server, connOpts)
```
Comment (oleg-jukovec) [inline test_helpers/pool_helper.go:196]: We could add `ctx` as a first arg of the function.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
The code is not the same as in the previous implementation. The previous implementation have a timeout by default. The current code have an infinity timeout.

So we need to use a context default timeout in all tests/examples/inner calls (or pass a context to it).

```
tarantool.Connect(context.Background(), server, opts)
```

File: dial_test.go [hunk 11]
```diff
@@ -73,7 +74,9 @@ func TestDialer_Dial_passedOpts(t *testing.T) {
 	}
 
 	dialer := &mockPassedDialer{}
-	conn, err := tarantool.Connect(addr, tarantool.Opts{
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
+	conn, err := tarantool.Connect(ctx, addr, tarantool.Opts{
```
Comment (oleg-jukovec) [inline dial_test.go:79]: You don't check that the user context is just passed into the dialer without any modification.

File: dial_test.go
Comment (oleg-jukovec) [inline dial_test.go:1]: There are now new tests with the new API functionality (context).

File: pool/connection_pool.go [hunk 12]
```diff
@@ -170,7 +173,9 @@ func ConnectWithOpts(addrs []string, connOpts tarantool.Opts, opts Opts) (*Conne
 	connPool.state.set(connectedState)
 
 	for _, s := range connPool.addrs {
-		go connPool.controller(s)
+		controllerCtx, cancel := context.WithCancel(context.Background())
+		connPool.ctxCancels = append(connPool.ctxCancels, cancel)
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:177]: We could use a single context with a single cancel function here.

File: ssl_test.go [hunk 13]
```diff
@@ -645,6 +646,79 @@ func TestSslOpts(t *testing.T) {
 	}
 }
 
+func TestSslDialContext(t *testing.T) {
+	serverOpts := SslOpts{
```
Comment (oleg-jukovec) [inline ssl_test.go:650]: What does this test check?

File: connection.go [hunk 14]
```diff
@@ -658,34 +643,46 @@ func pack(h *smallWBuf, enc *msgpack.Encoder, reqid uint32,
...
+	waitLoop:
+		for {
+			select {
+			case <-ctx.Done():
+				conn.mutex.Lock()
+				return ClientError{ErrConnectionClosed, "operation was canceled"}
+			case <-timer.C:
+				break waitLoop
+			}
+		}
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go:678]: Between reconnects we sleep for conn.opts.Reconnect seconds. So I added a loop with a timer. If a user cancels a context while we are waiting for the next reconnect, the function will return without any additional sleep.

File: ssl_test.go (hunk 13 above)
Comment (DerekBum) [reply ssl_test.go:650]: That dialContext works as regular dial (if we are not canceling it).

File: connection.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply connection.go:678]: A user should not cancel a contex between reconnects (because a user context is not used in reconnects).

File: ssl_test.go [hunk 15]
```diff
@@ -645,6 +646,79 @@ func TestSslOpts(t *testing.T) {
...
+	}
+
+	serverSslAccept(l)
+
+	port := l.Addr().(*net.TCPAddr).Port
+	_, err = SslDialContext(ctx, "tcp", sslHost+":"+strconv.Itoa(port), clientOpts)
+
+	if err == nil {
+		t.Fatalf("Expected error, dial was not canceled")
+	}
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply ssl_test.go:719]: It is actually our implementation, so we could check the error.

File: ssl_test.go (hunk 13 above)
Comment (oleg-jukovec) [reply ssl_test.go:650]: So we could add the case with context to here, there is no need in a separate test case.
https://github.com/tarantool/go-tarantool/blob/master/ssl_test.go#L251

File: CHANGELOG.md [hunk 16]
```diff
@@ -28,6 +28,9 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
   decoded to a varbinary object (#313).
 - Use objects of the Decimal type instead of pointers (#238)
 - Use objects of the Datetime type instead of pointers (#238)
+- `connection.Connect` and `pool.Connect` no longer return non-working 
+  connection objects (#136). Those functions now accept context as their first 
+  arguments, which user may cancel in process.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply CHANGELOG.md:33]: Is `ExampleConnect_reconnects` 
https://github.com/tarantool/go-tarantool/blob/e3e28fab1734199c598828554610368952ff9023/example_test.go#L938-L971
works as an example for reproducing a previous behavior of the `connection.Connect` function? Or is it needs to be in a README file?

[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply CHANGELOG.md:33]: Yes, it is fine. `opts.Reconnect`/`opts.MaxReconnects` instead of `reconnect` and `maxReconnects` to make the example more clear.

[the remark this answers is not in the document]
Comment (DerekBum) [reply CHANGELOG.md:33]: Updated.

File: README.md (hunk 7 above)
Comment (DerekBum) [reply README.md]: Updated. All tests now use either a context with timeout or a context with cancel.

File: connection.go [hunk 17]
```diff
@@ -534,18 +518,19 @@ func (conn *Connection) cancelFuture(fut *Future, err error) {
...
+func (conn *Connection) dial(ctx context.Context) (err error) {
 	opts := conn.opts
 	dialTimeout := opts.Reconnect / 2
 	if dialTimeout == 0 {
 		dialTimeout = 500 * time.Millisecond
 	} else if dialTimeout > 5*time.Second {
 		dialTimeout = 5 * time.Second
 	}
+	nestedCtx, cancel := context.WithTimeout(ctx, dialTimeout)
+	defer cancel()
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Updated.

File: connection.go [hunk 18]
```diff
@@ -381,10 +381,11 @@ func (opts Opts) Clone() Opts {
...
 // or error is returned.
 //
-// - If opts.Reconnect is non-zero, then error will be returned only if authorization
-// fails. But if Tarantool is not reachable, then it will make an attempt to reconnect later
-// and will not finish to make attempts on authorization failures.
-func Connect(addr string, opts Opts) (conn *Connection, err error) {
+// - If opts.Reconnect is non-zero, then error will be returned if authorization
+// fails, or user has canceled context. If Tarantool is not reachable, then it
+// will make attempts to reconnect and will not finish to make attempts on
+// authorization failures.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Yes, you are right. Updated.

File: connection.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Yes, you are right. Updated.

File: connection.go [hunk 19]
```diff
@@ -658,34 +643,46 @@ func pack(h *smallWBuf, enc *msgpack.Encoder, reqid uint32,
...
+		}
+
 		conn.mutex.Lock()
 	}
 	if conn.state == connClosed {
-		err = ClientError{ErrConnectionClosed, "using closed connection"}
+		return ClientError{ErrConnectionClosed, "using closed connection"}
 	}
-	return
+	return nil
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Yes, updated.

File: connection.go (hunk 8 above)
Comment (DerekBum) [reply connection.go]: Updated.

File: ssl_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply ssl_test.go]: Updated.

File: tarantool_test.go (hunk 9 above)
Comment (DerekBum) [reply tarantool_test.go]: Oops, updated.

File: test_helpers/pool_helper.go [hunk 20]
```diff
@@ -132,7 +133,7 @@ func Retry(f func(interface{}) error, args interface{}, count int, timeout time.
 
 func InsertOnInstance(server string, connOpts tarantool.Opts, space interface{},
 	tuple interface{}) error {
-	conn, err := tarantool.Connect(server, connOpts)
+	conn, err := tarantool.Connect(context.Background(), server, connOpts)
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply test_helpers/pool_helper.go]: Updated.

File: test_helpers/pool_helper.go (hunk 10 above)
Comment (DerekBum) [reply test_helpers/pool_helper.go]: Updated.

File: dial_test.go (hunk 11 above)
Comment (DerekBum) [reply dial_test.go]: Updated. Added more tests for dial.

File: dial_test.go
Comment (DerekBum) [reply dial_test.go:1]: Updated. Added more tests for dial.

File: pool/connection_pool.go (hunk 12 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Thanks, updated.

File: pool/connection_pool_test.go [hunk 21]
```diff
@@ -84,9 +86,41 @@ func TestConnSuccessfully(t *testing.T) {
...
+	wg.Add(1)
+
+	go func() {
+		defer wg.Done()
+		cancel()
+		connPool, err = pool.Connect(ctx, []string{"err"},
+			connLongReconnectOpts)
+	}()
+
+	wg.Wait()
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool_test.go]: Oops, updated.

File: ssl_test.go (hunk 13 above)
Comment (DerekBum) [reply ssl_test.go]: Updated.

File: connection.go [hunk 22]
```diff
@@ -658,34 +630,19 @@ func pack(h *smallWBuf, enc *msgpack.Encoder, reqid uint32,
...
-			err = ClientError{ErrConnectionClosed, "last reconnect failed"}
-			// mark connection as closed to avoid reopening by another goroutine
-			return
+func (conn *Connection) createConnection(ctx context.Context) error {
+	var err error
+	if conn.c == nil && conn.state == connDisconnected {
+		err = conn.dial(ctx)
+		if err == nil {
+			conn.notify(Connected)
+			return nil
```
Comment (oleg-jukovec) [inline connection.go:639]: It would be more clear.
```suggestion
	if conn.c == nil && conn.state == connDisconnected {
		if err := conn.dial(ctx); err == nil {
			conn.notify(Connected)
		}
		return err
```

File: connection.go [hunk 23]
```diff
@@ -727,11 +684,58 @@ func (conn *Connection) closeConnection(neterr error, forever bool) (err error)
...
+		if clientErr, ok := err.(ClientError); ok &&
+			clientErr.Code == ErrConnectionClosed {
+			return err
+		}
+
+		conn.opts.Logger.Report(LogReconnectFailed, conn, reconnects, err)
+		conn.notify(ReconnectFailed)
+		if conn.opts.MaxReconnects != 0 {
+			reconnects++
+		}
```
Comment (oleg-jukovec) [inline connection.go:721]: It is not clear from the first glance, please move `conn.opts.MaxReconnects == 0 || reconnects < conn.opts.MaxReconnects` in the loop condition.

File: connection.go [hunk 24]
```diff
@@ -727,11 +684,58 @@ func (conn *Connection) closeConnection(neterr error, forever bool) (err error)
...
+		err = conn.createConnection(ctx)
+		cancel()
+
+		if err == nil {
+			return nil
+		}
+		if clientErr, ok := err.(ClientError); ok &&
+			clientErr.Code == ErrConnectionClosed {
+			return err
+		}
```
Comment (oleg-jukovec) [inline connection.go:715]: if err != nil {
} else {
```suggestion
		if err != nil {
			if clientErr, ok := err.(ClientError); ok &&
				clientErr.Code == ErrConnectionClosed {
				return err
			}
		} else {
			return nil
		}
```

File: dial_test.go [hunk 25]
```diff
@@ -29,31 +32,37 @@ func TestDialer_Dial_error(t *testing.T) {
...
 
-	conn, err := tarantool.Connect("any", tarantool.Opts{
-		Dialer: dialer,
-	})
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
+	conn, err := tarantool.Connect(ctx, "any",
+		tarantool.Opts{
+			Dialer: dialer,
+		})
```
Comment (oleg-jukovec) [inline dial_test.go:40]: Just a codestyle, I don't see reasons for the change.
```suggestion
	conn, err := tarantool.Connect(ctx, "any",tarantool.Opts{
		Dialer: dialer,
	})
```

File: dial_test.go [hunk 26]
```diff
@@ -29,31 +32,37 @@ func TestDialer_Dial_error(t *testing.T) {
...
 }
 
-func (m *mockPassedDialer) Dial(address string,
+func (m *mockPassedDialer) Dial(ctx context.Context, address string,
 	opts tarantool.DialOpts) (tarantool.Conn, error) {
 	m.address = address
 	m.opts = opts
+	if ctx.Value("foo") != m.ctx.Value("foo") {
+		return nil, errors.New("wrong context")
+	}
```
Comment (oleg-jukovec) [inline dial_test.go:57]: Why don't just save/compare two context objects as for other options?

File: dial_test.go [hunk 27]
```diff
@@ -338,3 +360,19 @@ func TestConn_ReadWrite(t *testing.T) {
 	assert.Nil(t, err)
 	assert.NotNil(t, resp)
 }
+
+func TestConn_ContextCancel(t *testing.T) {
```
Comment (oleg-jukovec) [inline dial_test.go:364]: Could we test a cancellation in progress somehow?

File: example_custom_unpacking_test.go [hunk 28]
```diff
@@ -84,7 +85,9 @@ func Example_customUnpacking() {
 		User:          "test",
 		Pass:          "test",
 	}
-	conn, err := tarantool.Connect(server, opts)
+	ctx, cancel := context.WithTimeout(context.Background(), opts.Reconnect/2)
```
Comment (oleg-jukovec) [inline example_custom_unpacking_test.go:88]: Why not 500ms as in other tests?

File: example_test.go [hunk 29]
```diff
@@ -913,12 +917,51 @@ func ExampleFuture_GetIterator() {
...
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
+
+	conn, err := tarantool.Connect(ctx, "127.0.0.1:3013",
+		tarantool.Opts{
+			Timeout:     5 * time.Second,
+			User:        "test",
+			Pass:        "test",
+			Concurrency: 32,
+		})
```
Comment (oleg-jukovec) [inline example_test.go:929]: The same about the codestyle.
```suggestion
	conn, err := tarantool.Connect(ctx, "127.0.0.1:3013", tarantool.Opts{
		Timeout:     5 * time.Second,
		User:        "test",
		Pass:        "test",
		Concurrency: 32,
	})
```

File: example_test.go [hunk 30]
```diff
@@ -913,12 +917,51 @@ func ExampleFuture_GetIterator() {
...
+	if conn != nil {
+		fmt.Println("Connection is ready")
+	}
+	// Output:
+	// Connection is ready
+}
+
+func ExampleConnect_reconnects() {
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
```
Comment (oleg-jukovec) [inline example_test.go:944]: The context will expire after 500ms, but a Reconnect timeout is 5 seconds.

So there is wiil be only one try in fact.

File: export_test.go [hunk 31]
```diff
@@ -12,6 +13,11 @@ func SslDialTimeout(network, address string, timeout time.Duration,
 	return sslDialTimeout(network, address, timeout, opts)
```
Comment (oleg-jukovec) [inline export_test.go:13]: We don't need SslDialTimeout anymore.

File: go.mod [hunk 32]
```diff
@@ -8,7 +8,7 @@ require (
 	github.com/shopspring/decimal v1.3.1
 	github.com/stretchr/testify v1.7.1
 	github.com/tarantool/go-iproto v0.1.0
-	github.com/tarantool/go-openssl v0.0.8-0.20230801114713-b452431f934a
+	github.com/tarantool/go-openssl v0.0.8-0.20231002130016-e88579e113cf
```
Comment (oleg-jukovec) [inline go.mod:11]: Please, update to `336ca93`.

File: pool/connection_pool.go [hunk 33]
```diff
@@ -306,6 +318,9 @@ func (p *ConnectionPool) Close() []error {
 		}
 		p.addrsMutex.RUnlock()
 	}
+	for _, cancel := range p.ctxCancels {
+		cancel()
+	}
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:323]: The controller context and `endpoint.closed` channel is used for the same purpose. It controls a lifetime of a connection in the pool.

So you could replace `endpoint.closed` with the `cancel` object function and don't create a separate container for cancel functions + use the context object instead of the `endpoint.closed` channel.

File: pool/connection_pool.go [hunk 34]
```diff
@@ -1109,8 +1124,16 @@ func (p *ConnectionPool) handlerDeactivated(conn *tarantool.Connection,
...
 
-func (p *ConnectionPool) fillPools() bool {
+func (p *ConnectionPool) deactivateConnection(addr string,
+	conn *tarantool.Connection, role Role) {
+	p.deleteConnection(addr)
+	conn.Close()
+	p.handlerDeactivated(conn, role)
+}
+
+func (p *ConnectionPool) fillPools(ctx context.Context) (bool, bool) {
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:1134]: The method looks too complicated. Please, try to split it into several methods.

File: pool/connection_pool.go [hunk 35]
```diff
@@ -1120,9 +1143,26 @@ func (p *ConnectionPool) fillPools() bool {
...
+					if endpoint == nil {
+						continue
+					}
+					p.deactivateConnection(address, endpoint.conn, endpoint.role)
+				}
+
+				return false, ctxCanceled
+			default:
+			}
 		} else if conn != nil {
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:1166]: It there still possible now? conn == nil && err == nil.

File: ssl.go [hunk 36]
```diff
@@ -25,6 +26,16 @@ func sslDialTimeout(network, address string, timeout time.Duration,
 	return openssl.DialTimeout(network, address, timeout, ctx.(*openssl.Ctx), 0)
```
Comment (oleg-jukovec) [inline ssl.go:26]: We don't need sslDialTimeout anymore.

File: example_custom_unpacking_test.go (hunk 28 above)
Comment (DerekBum) [reply example_custom_unpacking_test.go:88]: In the previous implementation we used `opts.Reconnect/2` as timeout for `dial`. So now I thought it would be correct to use that value, instead of default hardcode (even tho they are equal). Another issue that I didn't put `Connect` inside a loop for `MaxReconnects` iterations (to match the previous test). 

Maybe I should use 500ms as `context.Timeout`, but also put `Connect` inside a loop for `MaxReconnects` iterations with a sleep for `Reconnect` seconds between them. And do so for every such test.

Comment (oleg-jukovec) [reply example_custom_unpacking_test.go:88]: The example is about unpacking, not about `Connect`. So the connection code could be easy.

File: tarantool_test.go [hunk 37]
```diff
@@ -708,7 +708,9 @@ func TestTtDialer(t *testing.T) {
 	assert := assert.New(t)
 	require := require.New(t)
 
-	conn, err := TtDialer{}.Dial(server, DialOpts{})
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
```
Comment (oleg-jukovec) [inline tarantool_test.go:712]: What about to create a test_helpers function to get a `Connect` context timeout for unite/integration-tests (but not for examples because it would be confusing for an example reader)?
```suggestion
	ctx, cancel := context.WithTimeout(context.Background(), test_helpers.GetTestConnectTimeout())
	defer cancel()
```

It would help us to change the timeout for all tests in the future.

Comment (DerekBum) [reply tarantool_test.go:712]: Will it be ok to add 2 helpers: `GetTestConnectTimeout` and `GetTestPoolConnectTimeout` (to manage pool connections)? In case we want to increase timeout for pool creations only.

File: pool/connection_pool.go (hunk 33 above)
Comment (oleg-jukovec) [reply pool/connection_pool.go:323]: If we want to replace `close` channel - yes, it is.

File: dial_test.go (hunk 27 above)
Comment (DerekBum) [reply dial_test.go:364]: I don't see a solution for this.

But I could create a mock dialer that would endlessly try to call `TtDialer.dial` (until the first error). Then call `mockdialer.Dial` and after some timeout cancel a context. It is not a 100% that we will cancel in progress, but it is a high chance (I suppose).

File: CHANGELOG.md [hunk 38]
```diff
@@ -28,6 +28,9 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
   decoded to a varbinary object (#313).
 - Use objects of the Decimal type instead of pointers (#238)
 - Use objects of the Datetime type instead of pointers (#238)
+- `connection.Connect` and `pool.Connect` no longer return non-working 
+  connection objects (#136). Those functions now accept context as their first
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply CHANGELOG.md]: Yes, updated.

File: README.md [hunk 39]
```diff
@@ -139,6 +145,10 @@ starting a session. There are two parameters:
 * a string with `host:port` format, and
 * the option structure that was set up earlier.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply README.md]: Yes, updated.

File: README.md [hunk 40]
```diff
@@ -167,10 +177,17 @@ The subpackage has been deleted. You could use `pool` instead.
 
 #### pool package
 
-The logic has not changed, but there are a few renames:
-
 * The `connection_pool` subpackage has been renamed to `pool`.
 * The type `PoolOpts` has been renamed to `Opts`.
+* `pool.Connect` no longer return non-working connection objects. This function 
+  now accepts context as first argument, which user may cancel in process.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply README.md]: Yes, updated.

File: README.md [hunk 41]
```diff
@@ -167,10 +177,17 @@ The subpackage has been deleted. You could use `pool` instead.
...
+* `pool.Add` now accepts context as first argument, which user may cancel in 
+  process.
+
+#### connection package
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply README.md]: Updated.

File: connection.go [hunk 42]
```diff
@@ -378,13 +378,9 @@ func (opts Opts) Clone() Opts {
...
 //
-// - If opts.Reconnect is zero (default), then connection either already connected
-// or error is returned.
-//
-// - If opts.Reconnect is non-zero, then error will be returned only if authorization
-// fails. But if Tarantool is not reachable, then it will make an attempt to reconnect later
-// and will not finish to make attempts on authorization failures.
-func Connect(addr string, opts Opts) (conn *Connection, err error) {
+// - There will be only one attempt to connect. If multiple attempts needed,
+// Connect could be placed inside the loop with some timeout between each try.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Updated.

File: connection.go [hunk 43]
```diff
@@ -534,18 +513,11 @@ func (conn *Connection) cancelFuture(fut *Future, err error) {
 	}
 }
 
-func (conn *Connection) dial() (err error) {
+func (conn *Connection) dial(ctx context.Context) (err error) {
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply connection.go]: Updated.

File: connection.go (hunk 22 above)
Comment (DerekBum) [reply connection.go]: Updated.

File: dial_test.go (hunk 25 above)
Comment (DerekBum) [reply dial_test.go]: Updated.

File: dial_test.go (hunk 27 above)
Comment (DerekBum) [reply dial_test.go:363]: Added a new test (as described above).

File: example_test.go (hunk 29 above)
Comment (DerekBum) [reply example_test.go]: Updated.

File: example_test.go (hunk 30 above)
Comment (DerekBum) [reply example_test.go]: Updated.

File: export_test.go (hunk 31 above)
Comment (DerekBum) [reply export_test.go]: SslDialTimeout deleted.

File: go.mod (hunk 32 above)
Comment (DerekBum) [reply go.mod]: Updated.

File: pool/connection_pool.go (hunk 33 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Updated. Now endpoint stores his context and cancel function.

File: pool/connection_pool.go (hunk 34 above)
Comment (DerekBum) [reply pool/connection_pool.go:1166]: Updated.

File: pool/connection_pool.go (hunk 35 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Yes, you are right, it is not possible. Updated.

File: tarantool_test.go (hunk 37 above)
Comment (DerekBum) [reply tarantool_test.go]: Updated (constant for `connection.Connect` is in `test_helpers/main.go`, for `pool.Connect` is in `test_helpers/pool_helper.go`).

File: tarantool_test.go [hunk 44]
```diff
@@ -4001,21 +4022,52 @@ func TestConnect_schema_update(t *testing.T) {
 	defer conn.Close()
 
 	for i := 0; i < 100; i++ {
-		fut := conn.Do(NewCallRequest("create_spaces"))
+		func() {
+			fut := conn.Do(NewCallRequest("create_spaces"))
```
Comment (oleg-jukovec) [inline tarantool_test.go:4026]: Concurrent `create_spaces` may conflict with each other.

The idea is that `create_spaces` is conturrent to a next connect. We don't need goroutines here because `conn.Do()` is async.

File: decimal/example_test.go [hunk 45]
```diff
@@ -28,7 +29,17 @@ func Example() {
...
+	var err error
+	for i := uint(0); i < opts.MaxReconnects; i++ {
+		ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+		client, err = tarantool.Connect(ctx, server, opts)
+		cancel()
+		if err == nil {
+			break
+		}
+		time.Sleep(opts.Reconnect)
+	}
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply decimal/example_test.go:42]: There were reconnects before (MaxReconnects and Reconnect were used in the `Connect`), and I tried not to change the behavior.

File: example_custom_unpacking_test.go [hunk 46]
```diff
@@ -84,7 +85,17 @@ func Example_customUnpacking() {
...
+	var err error
+	for i := uint(0); i < opts.MaxReconnects; i++ {
+		ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+		conn, err = tarantool.Connect(ctx, server, opts)
+		cancel()
+		if err == nil {
+			break
+		}
+		time.Sleep(opts.Reconnect)
+	}
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply example_custom_unpacking_test.go:98]: There were reconnects before (MaxReconnects and Reconnect were used in the Connect), and I tried not to change the behavior.

File: pool/connection_pool.go [hunk 47]
```diff
@@ -1109,8 +1119,53 @@ func (p *ConnectionPool) handlerDeactivated(conn *tarantool.Connection,
...
+		conn.Close()
+		log.Printf("tarantool: storing connection to %s failed: %s\n", addr, err)
+		return false
+	}
+
+	if p.handlerDiscovered(conn, role) {
+		if p.addConnection(addr, conn, role) != nil {
+			conn.Close()
+			p.handlerDeactivated(conn, role)
+		}
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go:1151]: There were no return in the original code. If we call `conn.Close()`, the conn state will be changed to `connClosed`. So, `ConnectedNow()` will return false (it check if the state is equal to `connConnected`). So, the only problem that could occur, is in implementation of `Deactivate` function for `handlerDeactivated` (but the error will be `log.Printf`-ed). But again, it is strange that there were no return previously.

File: tarantool_test.go (hunk 44 above)
Comment (DerekBum) [reply tarantool_test.go:4026]: There is no goroutines created. I used `func()` just so I could use `defer` inside a for loop without too much repeating (or I could move `Connect` call, cancel a context and then go to if-else branches). But there is no goroutines.

File: decimal/example_test.go (hunk 45 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply decimal/example_test.go:42]: The test not about reconnects, so let's remove the logic.

File: pool/connection_pool.go (hunk 47 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply pool/connection_pool.go:1151]: But is it call `p.handlerDeactivated` twice now?

File: tarantool_test.go (hunk 44 above)
Comment (oleg-jukovec) [reply tarantool_test.go:4026]: It is confusing.

I think you could just call `defer cancel()` in the loop. And it will be called x100 at the end of the tests - nothing will change.

File: pool/connection_pool.go (hunk 47 above)
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply pool/connection_pool.go:1151]: I think we could write the function in such manner. It would be less confusing and we will not miss anything:
```Go
func (p *ConnectionPool) processConnection(conn *tarantool.Connection,
	addr string, end *endpoint) bool {
	role, err := p.getConnectionRole(conn)
	if err != nil {
		conn.Close()
		log.Printf("tarantool: storing connection to %s failed: %s\n", addr, err)
		return false
	}

	if p.handlerDiscovered(conn, role) {
		if p.addConnection(addr, conn, role) == nil {
			end.conn = conn
			end.role = role
			return true
		}
		conn.Close()
		p.handlerDeactivated(conn, role)
	} else {
		conn.Close()
	}
	return false
}
```

File: pool/connection_pool.go [hunk 48]
```diff
@@ -115,25 +117,29 @@ type endpoint struct {
 	// This is used to switch a connection states.
 	shutdown chan struct{}
 	close    chan struct{}
-	closed   chan struct{}
+	ctx      context.Context
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply pool/connection_pool.go:120]: Could we just do:
`endpoint.close = ctx.Done()`

In some place in the endpoint creation?

File: CHANGELOG.md [hunk 49]
```diff
@@ -28,6 +28,10 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
   decoded to a varbinary object (#313).
 - Use objects of the Decimal type instead of pointers (#238)
 - Use objects of the Datetime type instead of pointers (#238)
+- `connection.Connect` no longer return non-working 
+  connection objects (#136). This function now does not attempt to reconnect 
+  and tries to establish a connection only once based on the context object. 
+  Context accepted as first argument, and user may cancel it in process.
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply CHANGELOG.md]: Updated.

File: decimal/example_test.go (hunk 45 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply decimal/example_test.go]: Updated.

File: dial_test.go [hunk 50]
```diff
@@ -338,3 +359,59 @@ func TestConn_ReadWrite(t *testing.T) {
...
+	opts.IoTimeout = 100 * time.Second
+	for {
+		_, err := dialer.Dial(ctx, address, opts)
+		if err != nil {
+			return nil, err
+		}
+	}
+}
+
+func TestConn_ContextCancelInProgress(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply dial_test.go]: Test removed.

File: example_custom_unpacking_test.go (hunk 46 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply example_custom_unpacking_test.go]: Updated.

File: pool/connection_pool.go (hunk 48 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go]: Updated. `close` and `closed` stays the same, new field `cancel` added to the `endpoint` struct.

File: pool/connection_pool.go (hunk 47 above)
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go]: Updated.

File: pool/connection_pool.go [hunk 51]
```diff
@@ -1109,8 +1119,53 @@ func (p *ConnectionPool) handlerDeactivated(conn *tarantool.Connection,
...
+	p.handlerDeactivated(conn, role)
+}
+
+func (p *ConnectionPool) deactivateConnections() {
+	for address, endpoint := range p.addrs {
+		if endpoint == nil {
+			continue
+		}
+		p.deactivateConnection(address, endpoint.conn, endpoint.role)
+	}
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go]: Yes, you are right. But conn will not be closed in this case, but nil (`endpoint.conn` is set only if everything is ok). Updated `if` statement.

File: pool/connection_pool.go [hunk 52]
```diff
@@ -1293,13 +1336,13 @@ func (p *ConnectionPool) controller(e *endpoint) {
 			// Graceful shutdown in progress. We need to wait for a finish or
 			// to force close.
 			select {
-			case <-e.closed:
+			case <-e.ctx.Done():
 			case <-e.close:
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply pool/connection_pool.go]: Updated. `close` and `closed` stays the same, new field `cancel` added to the `endpoint` struct.

File: shutdown_test.go [hunk 53]
```diff
@@ -460,9 +461,10 @@ func TestGracefulShutdownCloseConcurrent(t *testing.T) {
 		go func(i int) {
 			defer caseWg.Done()
 
-			// Do not wait till Tarantool register out watcher,
-			// test everything is ok even on async.
-			conn, err := Connect(shtdnServer, shtdnClntOpts)
+			ctx, cancel := context.WithTimeout(context.Background(),
+				test_helpers.GetConnectTimeout())
+			defer cancel()
+			conn, err := Connect(ctx, shtdnServer, shtdnClntOpts)
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply shutdown_test.go]: Updated.

File: pool/connection_pool.go [hunk 54]
```diff
@@ -224,9 +235,12 @@ func (p *ConnectionPool) ConfiguredTimeout(mode Mode) (time.Duration, error) {
 
 // Add adds a new endpoint with the address into the pool. This function
 // adds the endpoint only after successful connection.
-func (p *ConnectionPool) Add(addr string) error {
+func (p *ConnectionPool) Add(ctx context.Context, addr string) error {
 	e := newEndpoint(addr)
 
+	endpointCtx, cancel := context.WithCancel(context.Background())
+	e.cancel = cancel
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:242]: It is required to call the `e.cancel()` for all bad cases in the function.

File: pool/connection_pool.go [hunk 55]
```diff
@@ -1109,8 +1126,54 @@ func (p *ConnectionPool) handlerDeactivated(conn *tarantool.Connection,
...
+		conn.Close()
+		return false
+	}
+	if p.addConnection(addr, conn, role) != nil {
+		conn.Close()
+		p.handlerDeactivated(conn, role)
+		return false
+	}
+
+	if conn.ConnectedNow() {
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:1164]: I don't see a reason for the check. We already check that connection is alive in `getConnectionRole()` call.

File: pool/connection_pool.go [hunk 56]
```diff
@@ -1109,8 +1126,54 @@ func (p *ConnectionPool) handlerDeactivated(conn *tarantool.Connection,
...
+	conn.Close()
+	p.handlerDeactivated(conn, role)
+}
+
+func (p *ConnectionPool) deactivateConnections() {
+	for address, endpoint := range p.addrs {
+		if endpoint == nil || endpoint.conn == nil {
+			continue
+		}
+		p.deactivateConnection(address, endpoint.conn, endpoint.role)
```
Comment (oleg-jukovec) [inline pool/connection_pool.go:1141]: It is just simply.
```suggestion
		if endpoint != nil && endpoint.conn != nil {
			p.deactivateConnection(address, endpoint.conn, endpoint.role)
		}
```

**Review by oleg-jukovec — APPROVED** [review]
Thank you for the patch!

File: pool/connection_pool.go (hunk 56 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Updated.

File: pool/connection_pool.go (hunk 55 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Updated.

File: pool/connection_pool.go (hunk 54 above)
Comment (DerekBum) [reply pool/connection_pool.go]: Updated. I moved creation of the context, so it creates right before controller call.

File: crud/tarantool_test.go [hunk 57]
```diff
@@ -108,7 +108,9 @@ var object = crud.MapObject{
 
 func connect(t testing.TB) *tarantool.Connection {
 	for i := 0; i < 10; i++ {
-		conn, err := tarantool.Connect(server, opts)
+		ctx, cancel := test_helpers.GetConnectContext()
+		conn, err := tarantool.Connect(ctx, server, opts)
```
[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply crud/tarantool_test.go:112]: Yes, it is fine for Golang to have a default function with ctx.

[the remark this answers is not in the document]
Comment (DifferentialOrange) [reply crud/tarantool_test.go:112]: Seems a bit painful to rewrite all go-tarantool code, but let it be

[the remark this answers is not in the document]
Comment (oleg-jukovec) [reply crud/tarantool_test.go:112]: > Seems a bit painful to enforce all users to rewrite go-tarantool code, but let it be

I hope there will be more benefits from this. I also hope there shouldn’t be too many `Connect` calls in a client code.

File: CHANGELOG.md [hunk 58]
```diff
@@ -28,6 +28,12 @@ Versioning](http://semver.org/spec/v2.0.0.html) except to the first release.
...
+  `pool.Connect` and `pool.Add` now accept context as first argument, which
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply CHANGELOG.md:35]: Updated.

File: tarantool_test.go [hunk 59]
```diff
@@ -4019,6 +4035,32 @@ func TestConnect_schema_update(t *testing.T) {
...
+	ctx, cancel := context.WithCancel(context.Background())
+
+	var conn *Connection
+	var err error
+
+	cancel()
+	conn, err = Connect(ctx, server, connLongReconnectOpts)
+
+	if conn != nil || err == nil {
+		t.Fatalf("ConnectionPool was created after cancel")
```
[the remark this answers is not in the document]
Comment (DerekBum) [reply tarantool_test.go]: Updated.

**Review by oleg-jukovec — CHANGES_REQUESTED** [review]
Please, fix the problem and describe the fix/problem.
```
--- FAIL: TestAdd_CloseGraceful_concurrent (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9a8cec]

goroutine 301 [running]:
testing.tRunner.func1(0xc000106400)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x69f
panic(0xbe5d60, 0x111eb00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
github.com/tarantool/go-tarantool/v2/pool.(*ConnectionPool).CloseGraceful(0xc00011e8c0, 0xc95140, 0xc000350520, 0xc00011e8c0)
	/home/runner/work/go-tarantool/go-tarantool/pool/connection_pool.go:335 +0x13c
github.com/tarantool/go-tarantool/v2/pool_test.TestAdd_CloseGraceful_concurrent(0xc000106400)
	/home/runner/work/go-tarantool/go-tarantool/pool/connection_pool_test.go:487 +0x44f
testing.tRunner(0xc000106400, 0xc95148)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x652
FAIL	github.com/tarantool/go-tarantool/v2/pool	5.065s
```

**Comment by DerekBum** [comment]
Yeah, that happened because of this race:
1) In `Add` we are adding an endpoint to the map (`p.addrs[addr] = e`) inside a protected code (with locked `p.addrsMutex`). But after that we unlock the mutex, calling `tryConnect` and only after that initializing `cancel()` field for endpoint.
2) In `CloseGraceful` we are rlocking the `p.addrsMutex` and for each saved endpoint calling `cancel()` (may not be initialized).

So as a fix I did this: inside `Add` function initialize `cancel` in the protected part. In case of any error, we just cancel the created context. 

Note: there is no problem with `ConnectWithOpts`, because we can't use the new pool until we return from the function.

**Review by DifferentialOrange — APPROVED** [review]

**Review by oleg-jukovec — APPROVED** [review]
